using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Orleans.Http.CodeGenerator;

/// <summary>
/// Incremental source generator that scans for grain interfaces with HTTP routing attributes
/// (from Orleans.Http.Abstractions) and generates strongly-typed invocation delegates.
///
/// For each grain interface method that has [HttpGet]/[HttpPost]/[HttpPut]/[HttpDelete]/[HttpPatch]/[Route],
/// generates:
///   - A static Func&lt;IGrain, object?[], Task&gt; delegate for invoking the method
///   - A static Func&lt;Task, object?&gt; delegate for extracting the result (if Task&lt;T&gt;)
///
/// These delegates are registered in a static lookup table that GrainInvoker can use
/// instead of MethodInfo.Invoke, eliminating reflection overhead.
/// </summary>
[Generator]
public class GrainHttpSourceGenerator : IIncrementalGenerator
{
    private const string RouteAttribute = "Orleans.Http.Abstractions.RouteAttribute";

    private static readonly string[] HttpAttributeNames =
    [
        "Orleans.Http.Abstractions.HttpGetAttribute",
        "Orleans.Http.Abstractions.HttpPostAttribute",
        "Orleans.Http.Abstractions.HttpPutAttribute",
        "Orleans.Http.Abstractions.HttpDeleteAttribute",
        "Orleans.Http.Abstractions.HttpPatchAttribute",
        "Orleans.Http.Abstractions.RouteAttribute"
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all interface declarations that have methods with HTTP attributes
        var interfacesWithHttpMethods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsInterfaceWithHttpMethodAttributes(node),
                transform: static (ctx, _) => (InterfaceDeclarationSyntax)ctx.Node)
            .Where(static iface => iface is not null);

        // Combine with compilation to get semantic models
        var compilationAndInterfaces = context.CompilationProvider.Combine(interfacesWithHttpMethods.Collect());

        context.RegisterSourceOutput(compilationAndInterfaces, GenerateAllInvokers);
    }

    private static bool IsInterfaceWithHttpMethodAttributes(SyntaxNode node)
    {
        if (node is not InterfaceDeclarationSyntax iface) return false;
        return iface.Members.OfType<MethodDeclarationSyntax>().Any(m =>
            m.AttributeLists.SelectMany(al => al.Attributes).Any(a =>
                a.Name.ToString().Contains("HttpGet") ||
                a.Name.ToString().Contains("HttpPost") ||
                a.Name.ToString().Contains("HttpPut") ||
                a.Name.ToString().Contains("HttpDelete") ||
                a.Name.ToString().Contains("HttpPatch") ||
                a.Name.ToString() == "Route"));
    }

    private static void GenerateAllInvokers(SourceProductionContext context, (Compilation Compilation, System.Collections.Immutable.ImmutableArray<InterfaceDeclarationSyntax> Interfaces) data)
    {
        var (compilation, interfaces) = data;
        var seen = new System.Collections.Generic.HashSet<string>();

        foreach (var ifaceSyntax in interfaces)
        {
            if (ifaceSyntax is null) continue;

            var semanticModel = compilation.GetSemanticModel(ifaceSyntax.SyntaxTree);
            var symbol = semanticModel.GetDeclaredSymbol(ifaceSyntax) as INamedTypeSymbol;
            if (symbol is null) continue;

            // Check if this is a grain interface
            if (!IsGrainInterface(symbol)) continue;

            var fullKey = symbol.ToDisplayString();
            if (!seen.Add(fullKey)) continue; // deduplicate

            GenerateGrainInvoker(context, symbol);
        }
    }

    private static void GenerateGrainInvoker(SourceProductionContext context, INamedTypeSymbol symbol)
    {
        var namespaceName = symbol.ContainingNamespace?.ToDisplayString() ?? "Global";
        var interfaceName = symbol.ToDisplayString();
        var shortName = symbol.Name;
        var methods = symbol.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary && HasHttpAttribute(m))
            .ToList();

        if (methods.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine($"    internal static class {shortName}_HttpInvoker");
        sb.AppendLine("    {");

        for (int i = 0; i < methods.Count; i++)
        {
            var method = methods[i];
            var methodName = method.Name;
            var paramTypes = method.Parameters.Select(p => p.Type.ToDisplayString()).ToArray();
            var returnType = method.ReturnType;
            var isTaskOfT = returnType is INamedTypeSymbol { IsGenericType: true } namedType
                && namedType.OriginalDefinition.ToDisplayString() == "System.Threading.Tasks.Task<T>";

            // Generate the invocation delegate
            sb.AppendLine($"        // {methodName}: {returnType.ToDisplayString()}");
            sb.AppendLine($"        internal static global::System.Func<global::Orleans.IGrain, object?[], global::System.Threading.Tasks.Task> Invoke_{methodName} = (grain, args) =>");
            sb.Append($"            {{ {interfaceName} typed = ({interfaceName})grain;");

            if (paramTypes.Length == 0)
            {
                sb.AppendLine($" return typed.{methodName}(); }};");
            }
            else
            {
                sb.AppendLine();
                var args = new StringBuilder();
                for (int j = 0; j < paramTypes.Length; j++)
                {
                    if (j > 0) args.Append(", ");
                    args.Append($"({paramTypes[j]})args[{j}]!");
                }
                sb.AppendLine($"            return typed.{methodName}({args}); }};");
            }

            // Generate the result extraction delegate if Task<T>
            if (isTaskOfT)
            {
                var resultType = ((INamedTypeSymbol)returnType).TypeArguments[0];
                sb.AppendLine();
                sb.AppendLine($"        internal static global::System.Func<global::System.Threading.Tasks.Task, object?> GetResult_{methodName} = task =>");
                sb.AppendLine($"            ((global::System.Threading.Tasks.Task<{resultType.ToDisplayString()}>)task).GetAwaiter().GetResult();");
            }

            if (i < methods.Count - 1) sb.AppendLine();
        }

        sb.AppendLine("    }");

        // Generate a module initializer class that registers all delegates
        sb.AppendLine();
        sb.AppendLine($"    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine($"    internal static class {shortName}_HttpInvokerInit");
        sb.AppendLine("    {");
        sb.AppendLine($"        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"        internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var registry = global::Orleans.Http.HostingExtensions.GetGlobalInvokerRegistry();");
        sb.AppendLine($"        if (registry is null) return;");
        for (int i = 0; i < methods.Count; i++)
        {
            var method = methods[i];
            var methodName = method.Name;
            var interfaceType = interfaceName;
            sb.AppendLine($"        registry.RegisterInvoker(typeof({interfaceType}), \"{methodName}\", {shortName}_HttpInvoker.Invoke_{methodName});");

            var isTaskOfT = method.ReturnType is INamedTypeSymbol { IsGenericType: true } namedType
                && namedType.OriginalDefinition.ToDisplayString() == "System.Threading.Tasks.Task<T>";
            if (isTaskOfT)
            {
                sb.AppendLine($"        registry.RegisterResultExtractor(typeof({interfaceType}), \"{methodName}\", {shortName}_HttpInvoker.GetResult_{methodName});");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        var hintName = $"{namespaceName.Replace('.', '_')}.{shortName}_HttpInvoker.g.cs";
        context.AddSource(hintName, sb.ToString());
    }

    private static bool IsGrainInterface(INamedTypeSymbol symbol)
    {
        return symbol.AllInterfaces.Any(i =>
            i.ToDisplayString() == "Orleans.IGrain" ||
            i.ToDisplayString().StartsWith("Orleans.IGrainWith"));
    }

    private static bool HasHttpAttribute(IMethodSymbol method)
    {
        return method.GetAttributes().Any(a =>
        {
            var name = a.AttributeClass?.ToDisplayString();
            return name is not null && HttpAttributeNames.Contains(name);
        });
    }
}
